server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/montron_pm
    username: montron_pm
    password: montron_pm
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  flyway:
    enabled: true

form-api:
  base-url: http://localhost:8090

pm:
  export:
    base-directory: /mnt/montron-export
